mr#1
YuriyDubinin/test pull request #1
Opened 2024-07-26 10:27 UTC by YuriyDubinin

2024-07-26 11:37 UTC, lebenscode requested changes

2024-07-26 11:37 UTC, lebenscode commented on src/helpers/error.js
> +        this.status = `${statusCode}`.startsWith('4') ? 'fail' : 'error';
почему решил кастовать в строку, а не число проверять?

2024-07-26 11:37 UTC, lebenscode commented on src/helpers/error.js
> +    delete error?.statusCode;
зачем статус код удалять?

2024-07-26 11:37 UTC, lebenscode commented on src/helpers/fileSystem.js
> +    const userDirName = key;
зачем тут переменная новая? можно key переименовать в userDirName сразу

2024-07-26 11:37 UTC, lebenscode commented on src/helpers/fileSystem.js
> +            fs.mkdirSync(path.join(dir.static + `/users/${userDirName}`, 'videos'));
почему решил директории синхронно создавать? у тебя же fs/promises подключены

2024-07-26 11:37 UTC, lebenscode commented on src/helpers/fileSystem.js
> +        if (!fs.existsSync(path.join(dir.static + '/users', userDirName))) {
может сделать такую проверку для каждой директории, чтобы можно было досоздать то чего нет? в твоей версии если отвалится создание photos или videos, то ты их никак не создашь уже без ручных манипуляций

2024-07-26 11:37 UTC, lebenscode commented on src/helpers/fileSystem.js
> +const {v4} = require('uuid');
имхо : понятнее будет если переименовать v4 в uuid

2024-07-26 11:37 UTC, lebenscode commented on src/helpers/fileSystem.js
> +        file.mv(path.join(dir.static, `/users/${key}/${category}`, fileHash));
почему тут решил не обрабатывать ошибку fs?

2024-07-26 11:37 UTC, lebenscode commented on src/helpers/fileSystem.js
> +    const userDirName = key;
лишняя переменная

2024-07-26 11:37 UTC, lebenscode commented on src/helpers/fileSystem.js
> +        if (fs.existsSync(userDirPath)) {
проблема аналогичная createUserFileStructure, если отвалится удаление photos, то нужно руками доудалять остальное

2024-07-26 11:37 UTC, lebenscode commented on src/helpers/fileSystem.js
> +            fsPromises.rm(userDirPath, {recursive: true});
нужно же дождаться выполнения промисов и вся функция по-хорошему должна быть async

2024-07-26 11:37 UTC, lebenscode commented on src/helpers/validation.js
> +    min: 2,
выглядит лишним

2024-07-26 11:37 UTC, lebenscode commented on src/models/user.model.js
> +        const query = await db('users');
лишнее объявление переменной можно просто вернуть:
```suggestion
        return await db('users');
```

2024-07-26 11:37 UTC, lebenscode commented on src/models/user.model.js
> +        const query = await db('users').where({id});
лишняя переменная, аналогично комменту выше

2024-07-26 11:37 UTC, lebenscode commented on src/models/user.model.js
> +        const query = await db('users').insert({
лишняя переменная, аналогично комменту выше

2024-07-26 11:37 UTC, lebenscode commented on src/models/user.model.js
> +        const query = await db('users').where({id}).update({
лишняя переменная, аналогично комменту выше

2024-07-26 11:37 UTC, lebenscode commented on src/models/user.model.js
> +        const query = await db('users').where({id}).del();
лишняя переменная, аналогично комменту выше

2024-07-26 11:37 UTC, lebenscode commented on src/models/user.model.js
> +    async createUser(key, name, surname, patronymic, phone, email, address, photos, videos) {
не хочется модель собрать в сервисе и передать сюда? а тут уже маппером привести в вид нужный БД. Если у юзера будет 20 полей? или того хуже, каждое добавлять в сигнатуру функции выглядит не очень

2024-07-26 11:37 UTC, lebenscode commented on src/models/user.model.js
> +        const query = await db('users').where({key}).del();
лишняя переменная, аналогично комменту выше

2024-07-26 11:37 UTC, lebenscode commented on src/routes/user.routes.js
> +userRoutes.delete('/user/key', UserController.deleteUserByKey);
все роуты обернуть бы в middleware, которая распарсит параметры и прокинет в метод контроллера и обработает ответ

2024-07-26 11:37 UTC, lebenscode commented on src/services/user.service.js
> +        const users = await UserModel.getAllUsers();
нужно обработать ошибку БД тут и вернуть ошибку приложения выше, чтобы данные по бд не утекли

2024-07-26 11:37 UTC, lebenscode commented on src/services/user.service.js
> +        const id = parseInt(compositeKey.split('id=')[1]);
очень странный ключ, почему бы его не парсить еще в контроллере и не использовать метод getByUserId ?

2024-07-26 11:37 UTC, lebenscode commented on src/services/user.service.js
> +        return {id: result[0], key};
модель должна вернуть объект или просто айди. result[0] какой-то неявный контракт

2024-07-26 11:37 UTC, lebenscode commented on src/services/user.service.js
> +            photohashes = uploadUserFiles(key, 'photos', photos);
куда грузятся фотки, если папка под них еще не создана?

2024-07-26 11:37 UTC, lebenscode commented on src/services/user.service.js
> +            videohahses = uploadUserFiles(key, 'videos', videos);
такой же вопрос как и по фото

2024-07-26 11:37 UTC, lebenscode commented on src/services/user.service.js
> +        const result = await UserModel.updateUserById(
нужно обработать ошибку БД тут и вернуть ошибку приложения выше, чтобы данные по бд не утекли

2024-07-26 11:37 UTC, lebenscode commented on src/services/user.service.js
> +        const result = await UserModel.deleteUserById(id);
нужно обработать ошибку БД тут и вернуть ошибку приложения выше, чтобы данные по бд не утекли

2024-07-26 11:37 UTC, lebenscode commented on src/services/user.service.js
> +        const result = await UserModel.deleteUserByKey(key);
нужно обработать ошибку БД тут и вернуть ошибку приложения выше, чтобы данные по бд не утекли

2024-07-26 11:37 UTC, lebenscode commented on src/services/user.service.js
> +        await deleteUserFileStructureByKey(key);
deleteUserFileStructureByKey обычная функция и не вернет promise, надо сделать ее асинхронной

2024-07-26 12:15 UTC, YuriyDubinin commented on app.js
> +app.use((err, req, res, _) => {
потому что если параметра будет 3, экспресс распознает это как обычную мидлварину, а не как обработчик ошибок, а вот если у функции все 4 параметра - то тогда экспресс понимает что это обработчик ошибок, и не использует при ответе свою стандартную штмл загрушку

2024-07-26 12:18 UTC, YuriyDubinin commented on src/controllers/user.controller.js
> +                return passToNext(new AppError('Users not found', STATUS_CODES.NOT_FOUND));
Я думал над этим, но вообще она дергается при разных обстоятельствах, и я подумал что достаточно удобно просто при нужном условии дернуть ее и передать нужный текст там, код ошибки и иногда сам объект ошибки, как это происходит при валидации

2024-07-26 12:19 UTC, YuriyDubinin commented on src/controllers/user.controller.js
> +    async getAllUsers(req, res, passToNext) {
думаю да, можно, но мне показалось что я правильно уловил суть, что реквест поступает на вход контроллера, а внутри происзодит проверка внутренностей, не совсем уловил, в чем необходимость абстрагироваться от них?

2024-07-26 12:32 UTC, YuriyDubinin commented on src/controllers/user.controller.js
> +                new AppError(
это да, надо будет подумать что с этим сделать, не думал в таком разрезе, это был удобный момент при тестировании флоу, но в перспективе это надо будет устранить

2024-07-26 12:34 UTC, YuriyDubinin commented on src/controllers/user.controller.js
> +     * @param {string} name - User name.
не заметил при рефакторинге, исправил

2024-07-26 12:36 UTC, YuriyDubinin commented on src/controllers/user.controller.js
> +     * @param {string} patronymic - User patronymic.
в некоторых странах это используют как last name, но это применимо к народам, в которых у человека есть 2 имени, а потронумик как раз родовое имя, я это сам когда-то где-то увидел и подметил

2024-07-26 12:38 UTC, YuriyDubinin commented on src/helpers/dirConfig.js
> +    root: __dirname,
можно, но не видел в этом проблему, смысл был уйти от глобальных переменных и все

2024-07-26 12:55 UTC, YuriyDubinin commented on src/helpers/error.js
> +    delete error?.statusCode;
Это делается чтобы не было дубликации, так как далее по флоу sendResponse будет выводить статус кода на одном уровне с объектом ошибки

2024-07-26 12:56 UTC, YuriyDubinin commented on src/helpers/fileSystem.js
> +    const userDirName = key;
это проищошло из-за рефакторинга, это косяк, ранее userDirName был составной из ключа и еще некоторых штук, тут проебал просто удалить после рефакторинга

2024-07-26 13:02 UTC, YuriyDubinin commented on src/helpers/fileSystem.js
> +            fs.mkdirSync(path.join(dir.static + `/users/${userDirName}`, 'videos'));
изначальна реализация была с использованием модуля fs, потом при удалении наткнулся на варнинг что rmdirSync будет деприкейтед, решил проблему через fs/promise, но этот кусок не переписал, перепишу

2024-07-26 13:02 UTC, YuriyDubinin commented on src/helpers/fileSystem.js
> +        if (!fs.existsSync(path.join(dir.static + '/users', userDirName))) {
+

2024-07-26 13:03 UTC, YuriyDubinin commented on src/helpers/fileSystem.js
> +const {v4} = require('uuid');
без б, чисто с доки как взял так и на

2024-07-26 13:05 UTC, YuriyDubinin commented on src/helpers/fileSystem.js
> +        file.mv(path.join(dir.static, `/users/${key}/${category}`, fileHash));
это запара

2024-07-26 13:05 UTC, YuriyDubinin commented on src/helpers/fileSystem.js
> +    const userDirName = key;
да, я эти места поправил

2024-07-26 13:05 UTC, YuriyDubinin commented on src/helpers/fileSystem.js
> +        if (fs.existsSync(userDirPath)) {
поправлю по аналогии с описанным выше

2024-07-26 13:06 UTC, YuriyDubinin commented on src/helpers/validation.js
> +    min: 2,
это сделано намерено

2024-07-26 13:07 UTC, YuriyDubinin commented on src/helpers/fileSystem.js
> +            fsPromises.rm(userDirPath, {recursive: true});
все верно, этот модуль запарный, я перепишу его нормально на фс промисах с проверкамии и остальным необходимым

2024-07-26 13:09 UTC, YuriyDubinin commented on src/models/user.model.js
> +    async createUser(key, name, surname, patronymic, phone, email, address, photos, videos) {
идейно

2024-07-26 13:09 UTC, YuriyDubinin commented on src/services/user.service.js
> +        const result = await UserModel.updateUserById(
да

2024-07-26 13:11 UTC, YuriyDubinin commented on src/services/user.service.js
> +        await deleteUserFileStructureByKey(key);
Я переработаю весь модуль работы с файловой структурой

2024-07-26 13:47 UTC, lebenscode commented on src/controllers/user.controller.js
> +                return passToNext(new AppError('Users not found', STATUS_CODES.NOT_FOUND));
Ок, но 4 параметр идет в функцию handleError? ему бы имя дать, чтобы понятно стало чего это такое

2024-07-26 13:47 UTC, lebenscode commented on src/controllers/user.controller.js
> +    async getAllUsers(req, res, passToNext) {
убираешь дублирование кода и постоянные вызовы sendResponse и passToNext

2024-07-26 13:50 UTC, lebenscode commented on src/helpers/dirConfig.js
> +    root: __dirname,
при этом тебе надо постоянно подключать этот файл и знать где он находится. Подумать бы над di

2024-07-26 13:53 UTC, lebenscode commented on src/helpers/error.js
> +        this.status = `${statusCode}`.startsWith('4') ? 'fail' : 'error';
imho, кажется statusCode >= 400 && statusCode < 500 понятнее будет

2024-08-01 08:05 UTC, closed without merging

2024-08-01 08:05 UTC, YuriyDubinin commented
s